[package]
name = "dbxcase"
version = "0.1.0"
edition = "2021"

[dependencies.ureq]
optional = true
version = "2.9.7"

[features]
generate = ["dep:ureq"]

[[bin]]
name = "generate"
required-features = ["generate"]
